# 共享存储池
volumes:
  sqlite_data:
  static_volume:

#服务
services:
  # Django开发环境服务
  django-dev:
    build: 
      context: .
      dockerfile: Dockerfile.django.dev
    ports:
      - "8000:8000"
    volumes:
      - ./src/django:/app
      - sqlite_data:/app/db
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=1

  # nginx开发环境服务
  nginx-dev:
    build:
      context: .
      dockerfile: Dockerfile.nginx.dev
    ports:
      - "8080:80" # 转发端口至8080
    volumes:
      - ./src/html:/usr/share/nginx/html  # 实时同步开发文件
      - static_volume:/staticfiles
    environment:
      - NODE_ENV=development
    depends_on:
      - django-dev
  
  # 生产环境服务（本地测试用）
  # nginx-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:80"
  #   environment:
  #     - NODE_ENV=production

  # 可选：添加一个MySQL数据库服务
  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_DATABASE: mydb
  #   ports:
  #     - "3306:3306"